// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: luckyharness.proto

package luckyharness

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Chat
type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MaxIterations int32                  `protobuf:"varint,3,opt,name=max_iterations,json=maxIterations,proto3" json:"max_iterations,omitempty"`
	AutoApprove   bool                   `protobuf:"varint,4,opt,name=auto_approve,json=autoApprove,proto3" json:"auto_approve,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_luckyharness_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_luckyharness_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_luckyharness_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatRequest) GetMaxIterations() int32 {
	if x != nil {
		return x.MaxIterations
	}
	return 0
}

func (x *ChatRequest) GetAutoApprove() bool {
	if x != nil {
		return x.AutoApprove
	}
	return false
}

func (x *ChatRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Iterations    int32                  `protobuf:"varint,3,opt,name=iterations,proto3" json:"iterations,omitempty"`
	TokensUsed    int32                  `protobuf:"varint,4,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`
	ToolCalls     []*ToolCall            `protobuf:"bytes,5,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	Duration      string                 `protobuf:"bytes,6,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_luckyharness_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_luckyharness_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_luckyharness_proto_rawDescGZIP(), []int{1}
}

func (x *ChatResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *ChatResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatResponse) GetIterations() int32 {
	if x != nil {
		return x.Iterations
	}
	return 0
}

func (x *ChatResponse) GetTokensUsed() int32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

func (x *ChatResponse) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *ChatResponse) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

type ChatChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Done          bool                   `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatChunk) Reset() {
	*x = ChatChunk{}
	mi := &file_luckyharness_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatChunk) ProtoMessage() {}

func (x *ChatChunk) ProtoReflect() protoreflect.Message {
	mi := &file_luckyharness_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatChunk.ProtoReflect.Descriptor instead.
func (*ChatChunk) Descriptor() ([]byte, []int) {
	return file_luckyharness_proto_rawDescGZIP(), []int{2}
}

func (x *ChatChunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatChunk) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Arguments     string                 `protobuf:"bytes,2,opt,name=arguments,proto3" json:"arguments,omitempty"`
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Duration      string                 `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_luckyharness_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_luckyharness_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_luckyharness_proto_rawDescGZIP(), []int{3}
}

func (x *ToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCall) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

func (x *ToolCall) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ToolCall) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

// Memory
type MemoryStoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Tier          string                 `protobuf:"bytes,3,opt,name=tier,proto3" json:"tier,omitempty"`
	Importance    float64                `protobuf:"fixed64,4,opt,name=importance,proto3" json:"importance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryStoreRequest) Reset() {
	*x = MemoryStoreRequest{}
	mi := &file_luckyharness_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryStoreRequest) ProtoMessage() {}

func (x *MemoryStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_luckyharness_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryStoreRequest.ProtoReflect.Descriptor instead.
func (*MemoryStoreRequest) Descriptor() ([]byte, []int) {
	return file_luckyharness_proto_rawDescGZIP(), []int{4}
}

func (x *MemoryStoreRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MemoryStoreRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *MemoryStoreRequest) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *MemoryStoreRequest) GetImportance() float64 {
	if x != nil {
		return x.Importance
	}
	return 0
}

type MemoryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Tier          string                 `protobuf:"bytes,4,opt,name=tier,proto3" json:"tier,omitempty"`
	Importance    float64                `protobuf:"fixed64,5,opt,name=importance,proto3" json:"importance,omitempty"`
	AccessCount   int32                  `protobuf:"varint,6,opt,name=access_count,json=accessCount,proto3" json:"access_count,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryEntry) Reset() {
	*x = MemoryEntry{}
	mi := &file_luckyharness_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryEntry) ProtoMessage() {}

func (x *MemoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_luckyharness_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryEntry.ProtoReflect.Descriptor instead.
func (*MemoryEntry) Descriptor() ([]byte, []int) {
	return file_luckyharness_proto_rawDescGZIP(), []int{5}
}

func (x *MemoryEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MemoryEntry) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MemoryEntry) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *MemoryEntry) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *MemoryEntry) GetImportance() float64 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *MemoryEntry) GetAccessCount() int32 {
	if x != nil {
		return x.AccessCount
	}
	return 0
}

func (x *MemoryEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MemoryEntry) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type MemoryRecallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryRecallRequest) Reset() {
	*x = MemoryRecallRequest{}
	mi := &file_luckyharness_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryRecallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryRecallRequest) ProtoMessage() {}

func (x *MemoryRecallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_luckyharness_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryRecallRequest.ProtoReflect.Descriptor instead.
func (*MemoryRecallRequest) Descriptor() ([]byte, []int) {
	return file_luckyharness_proto_rawDescGZIP(), []int{6}
}

func (x *MemoryRecallRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *MemoryRecallRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *MemoryRecallRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type MemoryRecallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*MemoryEntry         `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryRecallResponse) Reset() {
	*x = MemoryRecallResponse{}
	mi := &file_luckyharness_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryRecallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryRecallResponse) ProtoMessage() {}

func (x *MemoryRecallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_luckyharness_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryRecallResponse.ProtoReflect.Descriptor instead.
func (*MemoryRecallResponse) Descriptor() ([]byte, []int) {
	return file_luckyharness_proto_rawDescGZIP(), []int{7}
}

func (x *MemoryRecallResponse) GetEntries() []*MemoryEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *MemoryRecallResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type MemoryListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*MemoryEntry         `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryListResponse) Reset() {
	*x = MemoryListResponse{}
	mi := &file_luckyharness_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryListResponse) ProtoMessage() {}

func (x *MemoryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_luckyharness_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryListResponse.ProtoReflect.Descriptor instead.
func (*MemoryListResponse) Descriptor() ([]byte, []int) {
	return file_luckyharness_proto_rawDescGZIP(), []int{8}
}

func (x *MemoryListResponse) GetEntries() []*MemoryEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *MemoryListResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type MemoryDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryDeleteRequest) Reset() {
	*x = MemoryDeleteRequest{}
	mi := &file_luckyharness_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryDeleteRequest) ProtoMessage() {}

func (x *MemoryDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_luckyharness_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryDeleteRequest.ProtoReflect.Descriptor instead.
func (*MemoryDeleteRequest) Descriptor() ([]byte, []int) {
	return file_luckyharness_proto_rawDescGZIP(), []int{9}
}

func (x *MemoryDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// RAG
type RAGIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RAGIndexRequest) Reset() {
	*x = RAGIndexRequest{}
	mi := &file_luckyharness_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RAGIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAGIndexRequest) ProtoMessage() {}

func (x *RAGIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_luckyharness_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAGIndexRequest.ProtoReflect.Descriptor instead.
func (*RAGIndexRequest) Descriptor() ([]byte, []int) {
	return file_luckyharness_proto_rawDescGZIP(), []int{10}
}

func (x *RAGIndexRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RAGIndexRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RAGIndexRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RAGIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Dimension     int32                  `protobuf:"varint,2,opt,name=dimension,proto3" json:"dimension,omitempty"`
	TotalEntries  int32                  `protobuf:"varint,3,opt,name=total_entries,json=totalEntries,proto3" json:"total_entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RAGIndexResponse) Reset() {
	*x = RAGIndexResponse{}
	mi := &file_luckyharness_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RAGIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAGIndexResponse) ProtoMessage() {}

func (x *RAGIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_luckyharness_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAGIndexResponse.ProtoReflect.Descriptor instead.
func (*RAGIndexResponse) Descriptor() ([]byte, []int) {
	return file_luckyharness_proto_rawDescGZIP(), []int{11}
}

func (x *RAGIndexResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RAGIndexResponse) GetDimension() int32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

func (x *RAGIndexResponse) GetTotalEntries() int32 {
	if x != nil {
		return x.TotalEntries
	}
	return 0
}

type RAGSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Threshold     float64                `protobuf:"fixed64,3,opt,name=threshold,proto3" json:"threshold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RAGSearchRequest) Reset() {
	*x = RAGSearchRequest{}
	mi := &file_luckyharness_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RAGSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAGSearchRequest) ProtoMessage() {}

func (x *RAGSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_luckyharness_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAGSearchRequest.ProtoReflect.Descriptor instead.
func (*RAGSearchRequest) Descriptor() ([]byte, []int) {
	return file_luckyharness_proto_rawDescGZIP(), []int{12}
}

func (x *RAGSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RAGSearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RAGSearchRequest) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

type RAGSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*RAGResult           `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RAGSearchResponse) Reset() {
	*x = RAGSearchResponse{}
	mi := &file_luckyharness_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RAGSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAGSearchResponse) ProtoMessage() {}

func (x *RAGSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_luckyharness_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAGSearchResponse.ProtoReflect.Descriptor instead.
func (*RAGSearchResponse) Descriptor() ([]byte, []int) {
	return file_luckyharness_proto_rawDescGZIP(), []int{13}
}

func (x *RAGSearchResponse) GetResults() []*RAGResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *RAGSearchResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RAGResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RAGResult) Reset() {
	*x = RAGResult{}
	mi := &file_luckyharness_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RAGResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAGResult) ProtoMessage() {}

func (x *RAGResult) ProtoReflect() protoreflect.Message {
	mi := &file_luckyharness_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAGResult.ProtoReflect.Descriptor instead.
func (*RAGResult) Descriptor() ([]byte, []int) {
	return file_luckyharness_proto_rawDescGZIP(), []int{14}
}

func (x *RAGResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RAGResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RAGResult) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RAGResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RAGResult) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Workflow
type WorkflowCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Tasks         []*Task                `protobuf:"bytes,3,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowCreateRequest) Reset() {
	*x = WorkflowCreateRequest{}
	mi := &file_luckyharness_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowCreateRequest) ProtoMessage() {}

func (x *WorkflowCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_luckyharness_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowCreateRequest.ProtoReflect.Descriptor instead.
func (*WorkflowCreateRequest) Descriptor() ([]byte, []int) {
	return file_luckyharness_proto_rawDescGZIP(), []int{15}
}

func (x *WorkflowCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkflowCreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WorkflowCreateRequest) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *WorkflowCreateRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	Params        map[string]string      `protobuf:"bytes,5,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DependsOn     []string               `protobuf:"bytes,6,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,7,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	RetryCount    int32                  `protobuf:"varint,8,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	RetryDelayMs  int64                  `protobuf:"varint,9,opt,name=retry_delay_ms,json=retryDelayMs,proto3" json:"retry_delay_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_luckyharness_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_luckyharness_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_luckyharness_proto_rawDescGZIP(), []int{16}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Task) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Task) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Task) GetDependsOn() []string {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

func (x *Task) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *Task) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *Task) GetRetryDelayMs() int64 {
	if x != nil {
		return x.RetryDelayMs
	}
	return 0
}

type Workflow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Tasks         []*Task                `protobuf:"bytes,4,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workflow) Reset() {
	*x = Workflow{}
	mi := &file_luckyharness_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workflow) ProtoMessage() {}

func (x *Workflow) ProtoReflect() protoreflect.Message {
	mi := &file_luckyharness_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workflow.ProtoReflect.Descriptor instead.
func (*Workflow) Descriptor() ([]byte, []int) {
	return file_luckyharness_proto_rawDescGZIP(), []int{17}
}

func (x *Workflow) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Workflow) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workflow) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Workflow) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *Workflow) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Workflow) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Workflow) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type WorkflowGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowGetRequest) Reset() {
	*x = WorkflowGetRequest{}
	mi := &file_luckyharness_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowGetRequest) ProtoMessage() {}

func (x *WorkflowGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_luckyharness_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowGetRequest.ProtoReflect.Descriptor instead.
func (*WorkflowGetRequest) Descriptor() ([]byte, []int) {
	return file_luckyharness_proto_rawDescGZIP(), []int{18}
}

func (x *WorkflowGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type WorkflowListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflows     []*Workflow            `protobuf:"bytes,1,rep,name=workflows,proto3" json:"workflows,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowListResponse) Reset() {
	*x = WorkflowListResponse{}
	mi := &file_luckyharness_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowListResponse) ProtoMessage() {}

func (x *WorkflowListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_luckyharness_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowListResponse.ProtoReflect.Descriptor instead.
func (*WorkflowListResponse) Descriptor() ([]byte, []int) {
	return file_luckyharness_proto_rawDescGZIP(), []int{19}
}

func (x *WorkflowListResponse) GetWorkflows() []*Workflow {
	if x != nil {
		return x.Workflows
	}
	return nil
}

func (x *WorkflowListResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type WorkflowDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowDeleteRequest) Reset() {
	*x = WorkflowDeleteRequest{}
	mi := &file_luckyharness_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowDeleteRequest) ProtoMessage() {}

func (x *WorkflowDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_luckyharness_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowDeleteRequest.ProtoReflect.Descriptor instead.
func (*WorkflowDeleteRequest) Descriptor() ([]byte, []int) {
	return file_luckyharness_proto_rawDescGZIP(), []int{20}
}

func (x *WorkflowDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type WorkflowStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowStartRequest) Reset() {
	*x = WorkflowStartRequest{}
	mi := &file_luckyharness_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowStartRequest) ProtoMessage() {}

func (x *WorkflowStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_luckyharness_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowStartRequest.ProtoReflect.Descriptor instead.
func (*WorkflowStartRequest) Descriptor() ([]byte, []int) {
	return file_luckyharness_proto_rawDescGZIP(), []int{21}
}

func (x *WorkflowStartRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type WorkflowInstance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Results       map[string]*TaskResult `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowInstance) Reset() {
	*x = WorkflowInstance{}
	mi := &file_luckyharness_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowInstance) ProtoMessage() {}

func (x *WorkflowInstance) ProtoReflect() protoreflect.Message {
	mi := &file_luckyharness_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowInstance.ProtoReflect.Descriptor instead.
func (*WorkflowInstance) Descriptor() ([]byte, []int) {
	return file_luckyharness_proto_rawDescGZIP(), []int{22}
}

func (x *WorkflowInstance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkflowInstance) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *WorkflowInstance) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkflowInstance) GetResults() map[string]*TaskResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *WorkflowInstance) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *WorkflowInstance) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	DurationMs    int64                  `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_luckyharness_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_luckyharness_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_luckyharness_proto_rawDescGZIP(), []int{23}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *TaskResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TaskResult) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *TaskResult) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *TaskResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type WorkflowInstanceGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowInstanceGetRequest) Reset() {
	*x = WorkflowInstanceGetRequest{}
	mi := &file_luckyharness_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowInstanceGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowInstanceGetRequest) ProtoMessage() {}

func (x *WorkflowInstanceGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_luckyharness_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowInstanceGetRequest.ProtoReflect.Descriptor instead.
func (*WorkflowInstanceGetRequest) Descriptor() ([]byte, []int) {
	return file_luckyharness_proto_rawDescGZIP(), []int{24}
}

func (x *WorkflowInstanceGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Health
type HealthCheckResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Status        string                      `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                      `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Uptime        *timestamppb.Timestamp      `protobuf:"bytes,3,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Components    map[string]*ComponentHealth `protobuf:"bytes,4,rep,name=components,proto3" json:"components,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_luckyharness_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_luckyharness_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_luckyharness_proto_rawDescGZIP(), []int{25}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetUptime() *timestamppb.Timestamp {
	if x != nil {
		return x.Uptime
	}
	return nil
}

func (x *HealthCheckResponse) GetComponents() map[string]*ComponentHealth {
	if x != nil {
		return x.Components
	}
	return nil
}

type ComponentHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentHealth) Reset() {
	*x = ComponentHealth{}
	mi := &file_luckyharness_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentHealth) ProtoMessage() {}

func (x *ComponentHealth) ProtoReflect() protoreflect.Message {
	mi := &file_luckyharness_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentHealth.ProtoReflect.Descriptor instead.
func (*ComponentHealth) Descriptor() ([]byte, []int) {
	return file_luckyharness_proto_rawDescGZIP(), []int{26}
}

func (x *ComponentHealth) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ComponentHealth) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_luckyharness_proto protoreflect.FileDescriptor

const file_luckyharness_proto_rawDesc = "" +
	"\n" +
	"\x12luckyharness.proto\x12\fluckyharness\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x92\x02\n" +
	"\vChatRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12%\n" +
	"\x0emax_iterations\x18\x03 \x01(\x05R\rmaxIterations\x12!\n" +
	"\fauto_approve\x18\x04 \x01(\bR\vautoApprove\x12C\n" +
	"\bmetadata\x18\x05 \x03(\v2'.luckyharness.ChatRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdd\x01\n" +
	"\fChatResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1e\n" +
	"\n" +
	"iterations\x18\x03 \x01(\x05R\n" +
	"iterations\x12\x1f\n" +
	"\vtokens_used\x18\x04 \x01(\x05R\n" +
	"tokensUsed\x125\n" +
	"\n" +
	"tool_calls\x18\x05 \x03(\v2\x16.luckyharness.ToolCallR\ttoolCalls\x12\x1a\n" +
	"\bduration\x18\x06 \x01(\tR\bduration\"X\n" +
	"\tChatChunk\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04done\x18\x03 \x01(\bR\x04done\"p\n" +
	"\bToolCall\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\targuments\x18\x02 \x01(\tR\targuments\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\tR\bduration\"~\n" +
	"\x12MemoryStoreRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x12\n" +
	"\x04tier\x18\x03 \x01(\tR\x04tier\x12\x1e\n" +
	"\n" +
	"importance\x18\x04 \x01(\x01R\n" +
	"importance\"\xa0\x02\n" +
	"\vMemoryEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x12\n" +
	"\x04tier\x18\x04 \x01(\tR\x04tier\x12\x1e\n" +
	"\n" +
	"importance\x18\x05 \x01(\x01R\n" +
	"importance\x12!\n" +
	"\faccess_count\x18\x06 \x01(\x05R\vaccessCount\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"]\n" +
	"\x13MemoryRecallRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\"a\n" +
	"\x14MemoryRecallResponse\x123\n" +
	"\aentries\x18\x01 \x03(\v2\x19.luckyharness.MemoryEntryR\aentries\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"_\n" +
	"\x12MemoryListResponse\x123\n" +
	"\aentries\x18\x01 \x03(\v2\x19.luckyharness.MemoryEntryR\aentries\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"%\n" +
	"\x13MemoryDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc9\x01\n" +
	"\x0fRAGIndexRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12G\n" +
	"\bmetadata\x18\x03 \x03(\v2+.luckyharness.RAGIndexRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"e\n" +
	"\x10RAGIndexResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tdimension\x18\x02 \x01(\x05R\tdimension\x12#\n" +
	"\rtotal_entries\x18\x03 \x01(\x05R\ftotalEntries\"\\\n" +
	"\x10RAGSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1c\n" +
	"\tthreshold\x18\x03 \x01(\x01R\tthreshold\"\\\n" +
	"\x11RAGSearchResponse\x121\n" +
	"\aresults\x18\x01 \x03(\v2\x17.luckyharness.RAGResultR\aresults\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xe3\x01\n" +
	"\tRAGResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12A\n" +
	"\bmetadata\x18\x05 \x03(\v2%.luckyharness.RAGResult.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x91\x01\n" +
	"\x15WorkflowCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12(\n" +
	"\x05tasks\x18\x03 \x03(\v2\x12.luckyharness.TaskR\x05tasks\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"\xdc\x02\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x126\n" +
	"\x06params\x18\x05 \x03(\v2\x1e.luckyharness.Task.ParamsEntryR\x06params\x12\x1d\n" +
	"\n" +
	"depends_on\x18\x06 \x03(\tR\tdependsOn\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\a \x01(\x03R\ttimeoutMs\x12\x1f\n" +
	"\vretry_count\x18\b \x01(\x05R\n" +
	"retryCount\x12$\n" +
	"\x0eretry_delay_ms\x18\t \x01(\x03R\fretryDelayMs\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8a\x02\n" +
	"\bWorkflow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12(\n" +
	"\x05tasks\x18\x04 \x03(\v2\x12.luckyharness.TaskR\x05tasks\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"$\n" +
	"\x12WorkflowGetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"b\n" +
	"\x14WorkflowListResponse\x124\n" +
	"\tworkflows\x18\x01 \x03(\v2\x16.luckyharness.WorkflowR\tworkflows\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"'\n" +
	"\x15WorkflowDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"7\n" +
	"\x14WorkflowStartRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\"\xea\x02\n" +
	"\x10WorkflowInstance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12E\n" +
	"\aresults\x18\x04 \x03(\v2+.luckyharness.WorkflowInstance.ResultsEntryR\aresults\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x1aT\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.luckyharness.TaskResultR\x05value:\x028\x01\"\xfe\x01\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x03R\n" +
	"durationMs\",\n" +
	"\x1aWorkflowInstanceGetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xac\x02\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x122\n" +
	"\x06uptime\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06uptime\x12Q\n" +
	"\n" +
	"components\x18\x04 \x03(\v21.luckyharness.HealthCheckResponse.ComponentsEntryR\n" +
	"components\x1a\\\n" +
	"\x0fComponentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.luckyharness.ComponentHealthR\x05value:\x028\x01\"C\n" +
	"\x0fComponentHealth\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xaf\r\n" +
	"\x13LuckyHarnessService\x12[\n" +
	"\x04Chat\x12\x19.luckyharness.ChatRequest\x1a\x1a.luckyharness.ChatResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/v1/grpc/chat\x12g\n" +
	"\n" +
	"ChatStream\x12\x19.luckyharness.ChatRequest\x1a\x17.luckyharness.ChatChunk\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/grpc/chat/stream0\x01\x12j\n" +
	"\vMemoryStore\x12 .luckyharness.MemoryStoreRequest\x1a\x19.luckyharness.MemoryEntry\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/grpc/memory\x12|\n" +
	"\fMemoryRecall\x12!.luckyharness.MemoryRecallRequest\x1a\".luckyharness.MemoryRecallResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/grpc/memory/recall\x12c\n" +
	"\n" +
	"MemoryList\x12\x16.google.protobuf.Empty\x1a .luckyharness.MemoryListResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/grpc/memory\x12k\n" +
	"\fMemoryDelete\x12!.luckyharness.MemoryDeleteRequest\x1a\x16.google.protobuf.Empty\" \x82\xd3\xe4\x93\x02\x1a*\x18/api/v1/grpc/memory/{id}\x12l\n" +
	"\bRAGIndex\x12\x1d.luckyharness.RAGIndexRequest\x1a\x1e.luckyharness.RAGIndexResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/grpc/rag/index\x12p\n" +
	"\tRAGSearch\x12\x1e.luckyharness.RAGSearchRequest\x1a\x1f.luckyharness.RAGSearchResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/grpc/rag/search\x12p\n" +
	"\x0eWorkflowCreate\x12#.luckyharness.WorkflowCreateRequest\x1a\x16.luckyharness.Workflow\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/grpc/workflows\x12l\n" +
	"\vWorkflowGet\x12 .luckyharness.WorkflowGetRequest\x1a\x16.luckyharness.Workflow\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/grpc/workflows/{id}\x12j\n" +
	"\fWorkflowList\x12\x16.google.protobuf.Empty\x1a\".luckyharness.WorkflowListResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/grpc/workflows\x12r\n" +
	"\x0eWorkflowDelete\x12#.luckyharness.WorkflowDeleteRequest\x1a\x16.google.protobuf.Empty\"#\x82\xd3\xe4\x93\x02\x1d*\x1b/api/v1/grpc/workflows/{id}\x12\x7f\n" +
	"\rWorkflowStart\x12\".luckyharness.WorkflowStartRequest\x1a\x1e.luckyharness.WorkflowInstance\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api/v1/grpc/workflow-instances\x12\x8d\x01\n" +
	"\x13WorkflowInstanceGet\x12(.luckyharness.WorkflowInstanceGetRequest\x1a\x1e.luckyharness.WorkflowInstance\",\x82\xd3\xe4\x93\x02&\x12$/api/v1/grpc/workflow-instances/{id}\x12e\n" +
	"\vHealthCheck\x12\x16.google.protobuf.Empty\x1a!.luckyharness.HealthCheckResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/grpc/healthB:Z8github.com/yurika0211/luckyharness/api/grpc;luckyharnessb\x06proto3"

var (
	file_luckyharness_proto_rawDescOnce sync.Once
	file_luckyharness_proto_rawDescData []byte
)

func file_luckyharness_proto_rawDescGZIP() []byte {
	file_luckyharness_proto_rawDescOnce.Do(func() {
		file_luckyharness_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_luckyharness_proto_rawDesc), len(file_luckyharness_proto_rawDesc)))
	})
	return file_luckyharness_proto_rawDescData
}

var file_luckyharness_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_luckyharness_proto_goTypes = []any{
	(*ChatRequest)(nil),                // 0: luckyharness.ChatRequest
	(*ChatResponse)(nil),               // 1: luckyharness.ChatResponse
	(*ChatChunk)(nil),                  // 2: luckyharness.ChatChunk
	(*ToolCall)(nil),                   // 3: luckyharness.ToolCall
	(*MemoryStoreRequest)(nil),         // 4: luckyharness.MemoryStoreRequest
	(*MemoryEntry)(nil),                // 5: luckyharness.MemoryEntry
	(*MemoryRecallRequest)(nil),        // 6: luckyharness.MemoryRecallRequest
	(*MemoryRecallResponse)(nil),       // 7: luckyharness.MemoryRecallResponse
	(*MemoryListResponse)(nil),         // 8: luckyharness.MemoryListResponse
	(*MemoryDeleteRequest)(nil),        // 9: luckyharness.MemoryDeleteRequest
	(*RAGIndexRequest)(nil),            // 10: luckyharness.RAGIndexRequest
	(*RAGIndexResponse)(nil),           // 11: luckyharness.RAGIndexResponse
	(*RAGSearchRequest)(nil),           // 12: luckyharness.RAGSearchRequest
	(*RAGSearchResponse)(nil),          // 13: luckyharness.RAGSearchResponse
	(*RAGResult)(nil),                  // 14: luckyharness.RAGResult
	(*WorkflowCreateRequest)(nil),      // 15: luckyharness.WorkflowCreateRequest
	(*Task)(nil),                       // 16: luckyharness.Task
	(*Workflow)(nil),                   // 17: luckyharness.Workflow
	(*WorkflowGetRequest)(nil),         // 18: luckyharness.WorkflowGetRequest
	(*WorkflowListResponse)(nil),       // 19: luckyharness.WorkflowListResponse
	(*WorkflowDeleteRequest)(nil),      // 20: luckyharness.WorkflowDeleteRequest
	(*WorkflowStartRequest)(nil),       // 21: luckyharness.WorkflowStartRequest
	(*WorkflowInstance)(nil),           // 22: luckyharness.WorkflowInstance
	(*TaskResult)(nil),                 // 23: luckyharness.TaskResult
	(*WorkflowInstanceGetRequest)(nil), // 24: luckyharness.WorkflowInstanceGetRequest
	(*HealthCheckResponse)(nil),        // 25: luckyharness.HealthCheckResponse
	(*ComponentHealth)(nil),            // 26: luckyharness.ComponentHealth
	nil,                                // 27: luckyharness.ChatRequest.MetadataEntry
	nil,                                // 28: luckyharness.RAGIndexRequest.MetadataEntry
	nil,                                // 29: luckyharness.RAGResult.MetadataEntry
	nil,                                // 30: luckyharness.Task.ParamsEntry
	nil,                                // 31: luckyharness.WorkflowInstance.ResultsEntry
	nil,                                // 32: luckyharness.HealthCheckResponse.ComponentsEntry
	(*timestamppb.Timestamp)(nil),      // 33: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 34: google.protobuf.Empty
}
var file_luckyharness_proto_depIdxs = []int32{
	27, // 0: luckyharness.ChatRequest.metadata:type_name -> luckyharness.ChatRequest.MetadataEntry
	3,  // 1: luckyharness.ChatResponse.tool_calls:type_name -> luckyharness.ToolCall
	33, // 2: luckyharness.MemoryEntry.created_at:type_name -> google.protobuf.Timestamp
	33, // 3: luckyharness.MemoryEntry.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 4: luckyharness.MemoryRecallResponse.entries:type_name -> luckyharness.MemoryEntry
	5,  // 5: luckyharness.MemoryListResponse.entries:type_name -> luckyharness.MemoryEntry
	28, // 6: luckyharness.RAGIndexRequest.metadata:type_name -> luckyharness.RAGIndexRequest.MetadataEntry
	14, // 7: luckyharness.RAGSearchResponse.results:type_name -> luckyharness.RAGResult
	29, // 8: luckyharness.RAGResult.metadata:type_name -> luckyharness.RAGResult.MetadataEntry
	16, // 9: luckyharness.WorkflowCreateRequest.tasks:type_name -> luckyharness.Task
	30, // 10: luckyharness.Task.params:type_name -> luckyharness.Task.ParamsEntry
	16, // 11: luckyharness.Workflow.tasks:type_name -> luckyharness.Task
	33, // 12: luckyharness.Workflow.created_at:type_name -> google.protobuf.Timestamp
	33, // 13: luckyharness.Workflow.updated_at:type_name -> google.protobuf.Timestamp
	17, // 14: luckyharness.WorkflowListResponse.workflows:type_name -> luckyharness.Workflow
	31, // 15: luckyharness.WorkflowInstance.results:type_name -> luckyharness.WorkflowInstance.ResultsEntry
	33, // 16: luckyharness.WorkflowInstance.start_time:type_name -> google.protobuf.Timestamp
	33, // 17: luckyharness.WorkflowInstance.end_time:type_name -> google.protobuf.Timestamp
	33, // 18: luckyharness.TaskResult.start_time:type_name -> google.protobuf.Timestamp
	33, // 19: luckyharness.TaskResult.end_time:type_name -> google.protobuf.Timestamp
	33, // 20: luckyharness.HealthCheckResponse.uptime:type_name -> google.protobuf.Timestamp
	32, // 21: luckyharness.HealthCheckResponse.components:type_name -> luckyharness.HealthCheckResponse.ComponentsEntry
	23, // 22: luckyharness.WorkflowInstance.ResultsEntry.value:type_name -> luckyharness.TaskResult
	26, // 23: luckyharness.HealthCheckResponse.ComponentsEntry.value:type_name -> luckyharness.ComponentHealth
	0,  // 24: luckyharness.LuckyHarnessService.Chat:input_type -> luckyharness.ChatRequest
	0,  // 25: luckyharness.LuckyHarnessService.ChatStream:input_type -> luckyharness.ChatRequest
	4,  // 26: luckyharness.LuckyHarnessService.MemoryStore:input_type -> luckyharness.MemoryStoreRequest
	6,  // 27: luckyharness.LuckyHarnessService.MemoryRecall:input_type -> luckyharness.MemoryRecallRequest
	34, // 28: luckyharness.LuckyHarnessService.MemoryList:input_type -> google.protobuf.Empty
	9,  // 29: luckyharness.LuckyHarnessService.MemoryDelete:input_type -> luckyharness.MemoryDeleteRequest
	10, // 30: luckyharness.LuckyHarnessService.RAGIndex:input_type -> luckyharness.RAGIndexRequest
	12, // 31: luckyharness.LuckyHarnessService.RAGSearch:input_type -> luckyharness.RAGSearchRequest
	15, // 32: luckyharness.LuckyHarnessService.WorkflowCreate:input_type -> luckyharness.WorkflowCreateRequest
	18, // 33: luckyharness.LuckyHarnessService.WorkflowGet:input_type -> luckyharness.WorkflowGetRequest
	34, // 34: luckyharness.LuckyHarnessService.WorkflowList:input_type -> google.protobuf.Empty
	20, // 35: luckyharness.LuckyHarnessService.WorkflowDelete:input_type -> luckyharness.WorkflowDeleteRequest
	21, // 36: luckyharness.LuckyHarnessService.WorkflowStart:input_type -> luckyharness.WorkflowStartRequest
	24, // 37: luckyharness.LuckyHarnessService.WorkflowInstanceGet:input_type -> luckyharness.WorkflowInstanceGetRequest
	34, // 38: luckyharness.LuckyHarnessService.HealthCheck:input_type -> google.protobuf.Empty
	1,  // 39: luckyharness.LuckyHarnessService.Chat:output_type -> luckyharness.ChatResponse
	2,  // 40: luckyharness.LuckyHarnessService.ChatStream:output_type -> luckyharness.ChatChunk
	5,  // 41: luckyharness.LuckyHarnessService.MemoryStore:output_type -> luckyharness.MemoryEntry
	7,  // 42: luckyharness.LuckyHarnessService.MemoryRecall:output_type -> luckyharness.MemoryRecallResponse
	8,  // 43: luckyharness.LuckyHarnessService.MemoryList:output_type -> luckyharness.MemoryListResponse
	34, // 44: luckyharness.LuckyHarnessService.MemoryDelete:output_type -> google.protobuf.Empty
	11, // 45: luckyharness.LuckyHarnessService.RAGIndex:output_type -> luckyharness.RAGIndexResponse
	13, // 46: luckyharness.LuckyHarnessService.RAGSearch:output_type -> luckyharness.RAGSearchResponse
	17, // 47: luckyharness.LuckyHarnessService.WorkflowCreate:output_type -> luckyharness.Workflow
	17, // 48: luckyharness.LuckyHarnessService.WorkflowGet:output_type -> luckyharness.Workflow
	19, // 49: luckyharness.LuckyHarnessService.WorkflowList:output_type -> luckyharness.WorkflowListResponse
	34, // 50: luckyharness.LuckyHarnessService.WorkflowDelete:output_type -> google.protobuf.Empty
	22, // 51: luckyharness.LuckyHarnessService.WorkflowStart:output_type -> luckyharness.WorkflowInstance
	22, // 52: luckyharness.LuckyHarnessService.WorkflowInstanceGet:output_type -> luckyharness.WorkflowInstance
	25, // 53: luckyharness.LuckyHarnessService.HealthCheck:output_type -> luckyharness.HealthCheckResponse
	39, // [39:54] is the sub-list for method output_type
	24, // [24:39] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_luckyharness_proto_init() }
func file_luckyharness_proto_init() {
	if File_luckyharness_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_luckyharness_proto_rawDesc), len(file_luckyharness_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_luckyharness_proto_goTypes,
		DependencyIndexes: file_luckyharness_proto_depIdxs,
		MessageInfos:      file_luckyharness_proto_msgTypes,
	}.Build()
	File_luckyharness_proto = out.File
	file_luckyharness_proto_goTypes = nil
	file_luckyharness_proto_depIdxs = nil
}
