// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: luckyharness.proto

package luckyharness

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LuckyHarnessService_Chat_FullMethodName                = "/luckyharness.LuckyHarnessService/Chat"
	LuckyHarnessService_ChatStream_FullMethodName          = "/luckyharness.LuckyHarnessService/ChatStream"
	LuckyHarnessService_MemoryStore_FullMethodName         = "/luckyharness.LuckyHarnessService/MemoryStore"
	LuckyHarnessService_MemoryRecall_FullMethodName        = "/luckyharness.LuckyHarnessService/MemoryRecall"
	LuckyHarnessService_MemoryList_FullMethodName          = "/luckyharness.LuckyHarnessService/MemoryList"
	LuckyHarnessService_MemoryDelete_FullMethodName        = "/luckyharness.LuckyHarnessService/MemoryDelete"
	LuckyHarnessService_RAGIndex_FullMethodName            = "/luckyharness.LuckyHarnessService/RAGIndex"
	LuckyHarnessService_RAGSearch_FullMethodName           = "/luckyharness.LuckyHarnessService/RAGSearch"
	LuckyHarnessService_WorkflowCreate_FullMethodName      = "/luckyharness.LuckyHarnessService/WorkflowCreate"
	LuckyHarnessService_WorkflowGet_FullMethodName         = "/luckyharness.LuckyHarnessService/WorkflowGet"
	LuckyHarnessService_WorkflowList_FullMethodName        = "/luckyharness.LuckyHarnessService/WorkflowList"
	LuckyHarnessService_WorkflowDelete_FullMethodName      = "/luckyharness.LuckyHarnessService/WorkflowDelete"
	LuckyHarnessService_WorkflowStart_FullMethodName       = "/luckyharness.LuckyHarnessService/WorkflowStart"
	LuckyHarnessService_WorkflowInstanceGet_FullMethodName = "/luckyharness.LuckyHarnessService/WorkflowInstanceGet"
	LuckyHarnessService_HealthCheck_FullMethodName         = "/luckyharness.LuckyHarnessService/HealthCheck"
)

// LuckyHarnessServiceClient is the client API for LuckyHarnessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LuckyHarness gRPC Service
type LuckyHarnessServiceClient interface {
	// Chat
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
	ChatStream(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatChunk], error)
	// Memory
	MemoryStore(ctx context.Context, in *MemoryStoreRequest, opts ...grpc.CallOption) (*MemoryEntry, error)
	MemoryRecall(ctx context.Context, in *MemoryRecallRequest, opts ...grpc.CallOption) (*MemoryRecallResponse, error)
	MemoryList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*MemoryListResponse, error)
	MemoryDelete(ctx context.Context, in *MemoryDeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// RAG
	RAGIndex(ctx context.Context, in *RAGIndexRequest, opts ...grpc.CallOption) (*RAGIndexResponse, error)
	RAGSearch(ctx context.Context, in *RAGSearchRequest, opts ...grpc.CallOption) (*RAGSearchResponse, error)
	// Workflow
	WorkflowCreate(ctx context.Context, in *WorkflowCreateRequest, opts ...grpc.CallOption) (*Workflow, error)
	WorkflowGet(ctx context.Context, in *WorkflowGetRequest, opts ...grpc.CallOption) (*Workflow, error)
	WorkflowList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*WorkflowListResponse, error)
	WorkflowDelete(ctx context.Context, in *WorkflowDeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	WorkflowStart(ctx context.Context, in *WorkflowStartRequest, opts ...grpc.CallOption) (*WorkflowInstance, error)
	WorkflowInstanceGet(ctx context.Context, in *WorkflowInstanceGetRequest, opts ...grpc.CallOption) (*WorkflowInstance, error)
	// Health
	HealthCheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type luckyHarnessServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLuckyHarnessServiceClient(cc grpc.ClientConnInterface) LuckyHarnessServiceClient {
	return &luckyHarnessServiceClient{cc}
}

func (c *luckyHarnessServiceClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatResponse)
	err := c.cc.Invoke(ctx, LuckyHarnessService_Chat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *luckyHarnessServiceClient) ChatStream(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LuckyHarnessService_ServiceDesc.Streams[0], LuckyHarnessService_ChatStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, ChatChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LuckyHarnessService_ChatStreamClient = grpc.ServerStreamingClient[ChatChunk]

func (c *luckyHarnessServiceClient) MemoryStore(ctx context.Context, in *MemoryStoreRequest, opts ...grpc.CallOption) (*MemoryEntry, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemoryEntry)
	err := c.cc.Invoke(ctx, LuckyHarnessService_MemoryStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *luckyHarnessServiceClient) MemoryRecall(ctx context.Context, in *MemoryRecallRequest, opts ...grpc.CallOption) (*MemoryRecallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemoryRecallResponse)
	err := c.cc.Invoke(ctx, LuckyHarnessService_MemoryRecall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *luckyHarnessServiceClient) MemoryList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*MemoryListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemoryListResponse)
	err := c.cc.Invoke(ctx, LuckyHarnessService_MemoryList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *luckyHarnessServiceClient) MemoryDelete(ctx context.Context, in *MemoryDeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LuckyHarnessService_MemoryDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *luckyHarnessServiceClient) RAGIndex(ctx context.Context, in *RAGIndexRequest, opts ...grpc.CallOption) (*RAGIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RAGIndexResponse)
	err := c.cc.Invoke(ctx, LuckyHarnessService_RAGIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *luckyHarnessServiceClient) RAGSearch(ctx context.Context, in *RAGSearchRequest, opts ...grpc.CallOption) (*RAGSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RAGSearchResponse)
	err := c.cc.Invoke(ctx, LuckyHarnessService_RAGSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *luckyHarnessServiceClient) WorkflowCreate(ctx context.Context, in *WorkflowCreateRequest, opts ...grpc.CallOption) (*Workflow, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Workflow)
	err := c.cc.Invoke(ctx, LuckyHarnessService_WorkflowCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *luckyHarnessServiceClient) WorkflowGet(ctx context.Context, in *WorkflowGetRequest, opts ...grpc.CallOption) (*Workflow, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Workflow)
	err := c.cc.Invoke(ctx, LuckyHarnessService_WorkflowGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *luckyHarnessServiceClient) WorkflowList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*WorkflowListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowListResponse)
	err := c.cc.Invoke(ctx, LuckyHarnessService_WorkflowList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *luckyHarnessServiceClient) WorkflowDelete(ctx context.Context, in *WorkflowDeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LuckyHarnessService_WorkflowDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *luckyHarnessServiceClient) WorkflowStart(ctx context.Context, in *WorkflowStartRequest, opts ...grpc.CallOption) (*WorkflowInstance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowInstance)
	err := c.cc.Invoke(ctx, LuckyHarnessService_WorkflowStart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *luckyHarnessServiceClient) WorkflowInstanceGet(ctx context.Context, in *WorkflowInstanceGetRequest, opts ...grpc.CallOption) (*WorkflowInstance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowInstance)
	err := c.cc.Invoke(ctx, LuckyHarnessService_WorkflowInstanceGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *luckyHarnessServiceClient) HealthCheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, LuckyHarnessService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LuckyHarnessServiceServer is the server API for LuckyHarnessService service.
// All implementations must embed UnimplementedLuckyHarnessServiceServer
// for forward compatibility.
//
// LuckyHarness gRPC Service
type LuckyHarnessServiceServer interface {
	// Chat
	Chat(context.Context, *ChatRequest) (*ChatResponse, error)
	ChatStream(*ChatRequest, grpc.ServerStreamingServer[ChatChunk]) error
	// Memory
	MemoryStore(context.Context, *MemoryStoreRequest) (*MemoryEntry, error)
	MemoryRecall(context.Context, *MemoryRecallRequest) (*MemoryRecallResponse, error)
	MemoryList(context.Context, *emptypb.Empty) (*MemoryListResponse, error)
	MemoryDelete(context.Context, *MemoryDeleteRequest) (*emptypb.Empty, error)
	// RAG
	RAGIndex(context.Context, *RAGIndexRequest) (*RAGIndexResponse, error)
	RAGSearch(context.Context, *RAGSearchRequest) (*RAGSearchResponse, error)
	// Workflow
	WorkflowCreate(context.Context, *WorkflowCreateRequest) (*Workflow, error)
	WorkflowGet(context.Context, *WorkflowGetRequest) (*Workflow, error)
	WorkflowList(context.Context, *emptypb.Empty) (*WorkflowListResponse, error)
	WorkflowDelete(context.Context, *WorkflowDeleteRequest) (*emptypb.Empty, error)
	WorkflowStart(context.Context, *WorkflowStartRequest) (*WorkflowInstance, error)
	WorkflowInstanceGet(context.Context, *WorkflowInstanceGetRequest) (*WorkflowInstance, error)
	// Health
	HealthCheck(context.Context, *emptypb.Empty) (*HealthCheckResponse, error)
	mustEmbedUnimplementedLuckyHarnessServiceServer()
}

// UnimplementedLuckyHarnessServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLuckyHarnessServiceServer struct{}

func (UnimplementedLuckyHarnessServiceServer) Chat(context.Context, *ChatRequest) (*ChatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedLuckyHarnessServiceServer) ChatStream(*ChatRequest, grpc.ServerStreamingServer[ChatChunk]) error {
	return status.Error(codes.Unimplemented, "method ChatStream not implemented")
}
func (UnimplementedLuckyHarnessServiceServer) MemoryStore(context.Context, *MemoryStoreRequest) (*MemoryEntry, error) {
	return nil, status.Error(codes.Unimplemented, "method MemoryStore not implemented")
}
func (UnimplementedLuckyHarnessServiceServer) MemoryRecall(context.Context, *MemoryRecallRequest) (*MemoryRecallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MemoryRecall not implemented")
}
func (UnimplementedLuckyHarnessServiceServer) MemoryList(context.Context, *emptypb.Empty) (*MemoryListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MemoryList not implemented")
}
func (UnimplementedLuckyHarnessServiceServer) MemoryDelete(context.Context, *MemoryDeleteRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method MemoryDelete not implemented")
}
func (UnimplementedLuckyHarnessServiceServer) RAGIndex(context.Context, *RAGIndexRequest) (*RAGIndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RAGIndex not implemented")
}
func (UnimplementedLuckyHarnessServiceServer) RAGSearch(context.Context, *RAGSearchRequest) (*RAGSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RAGSearch not implemented")
}
func (UnimplementedLuckyHarnessServiceServer) WorkflowCreate(context.Context, *WorkflowCreateRequest) (*Workflow, error) {
	return nil, status.Error(codes.Unimplemented, "method WorkflowCreate not implemented")
}
func (UnimplementedLuckyHarnessServiceServer) WorkflowGet(context.Context, *WorkflowGetRequest) (*Workflow, error) {
	return nil, status.Error(codes.Unimplemented, "method WorkflowGet not implemented")
}
func (UnimplementedLuckyHarnessServiceServer) WorkflowList(context.Context, *emptypb.Empty) (*WorkflowListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WorkflowList not implemented")
}
func (UnimplementedLuckyHarnessServiceServer) WorkflowDelete(context.Context, *WorkflowDeleteRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method WorkflowDelete not implemented")
}
func (UnimplementedLuckyHarnessServiceServer) WorkflowStart(context.Context, *WorkflowStartRequest) (*WorkflowInstance, error) {
	return nil, status.Error(codes.Unimplemented, "method WorkflowStart not implemented")
}
func (UnimplementedLuckyHarnessServiceServer) WorkflowInstanceGet(context.Context, *WorkflowInstanceGetRequest) (*WorkflowInstance, error) {
	return nil, status.Error(codes.Unimplemented, "method WorkflowInstanceGet not implemented")
}
func (UnimplementedLuckyHarnessServiceServer) HealthCheck(context.Context, *emptypb.Empty) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedLuckyHarnessServiceServer) mustEmbedUnimplementedLuckyHarnessServiceServer() {}
func (UnimplementedLuckyHarnessServiceServer) testEmbeddedByValue()                             {}

// UnsafeLuckyHarnessServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LuckyHarnessServiceServer will
// result in compilation errors.
type UnsafeLuckyHarnessServiceServer interface {
	mustEmbedUnimplementedLuckyHarnessServiceServer()
}

func RegisterLuckyHarnessServiceServer(s grpc.ServiceRegistrar, srv LuckyHarnessServiceServer) {
	// If the following call panics, it indicates UnimplementedLuckyHarnessServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LuckyHarnessService_ServiceDesc, srv)
}

func _LuckyHarnessService_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LuckyHarnessServiceServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LuckyHarnessService_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LuckyHarnessServiceServer).Chat(ctx, req.(*ChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LuckyHarnessService_ChatStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LuckyHarnessServiceServer).ChatStream(m, &grpc.GenericServerStream[ChatRequest, ChatChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LuckyHarnessService_ChatStreamServer = grpc.ServerStreamingServer[ChatChunk]

func _LuckyHarnessService_MemoryStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemoryStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LuckyHarnessServiceServer).MemoryStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LuckyHarnessService_MemoryStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LuckyHarnessServiceServer).MemoryStore(ctx, req.(*MemoryStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LuckyHarnessService_MemoryRecall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemoryRecallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LuckyHarnessServiceServer).MemoryRecall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LuckyHarnessService_MemoryRecall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LuckyHarnessServiceServer).MemoryRecall(ctx, req.(*MemoryRecallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LuckyHarnessService_MemoryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LuckyHarnessServiceServer).MemoryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LuckyHarnessService_MemoryList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LuckyHarnessServiceServer).MemoryList(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LuckyHarnessService_MemoryDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemoryDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LuckyHarnessServiceServer).MemoryDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LuckyHarnessService_MemoryDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LuckyHarnessServiceServer).MemoryDelete(ctx, req.(*MemoryDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LuckyHarnessService_RAGIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RAGIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LuckyHarnessServiceServer).RAGIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LuckyHarnessService_RAGIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LuckyHarnessServiceServer).RAGIndex(ctx, req.(*RAGIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LuckyHarnessService_RAGSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RAGSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LuckyHarnessServiceServer).RAGSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LuckyHarnessService_RAGSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LuckyHarnessServiceServer).RAGSearch(ctx, req.(*RAGSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LuckyHarnessService_WorkflowCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LuckyHarnessServiceServer).WorkflowCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LuckyHarnessService_WorkflowCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LuckyHarnessServiceServer).WorkflowCreate(ctx, req.(*WorkflowCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LuckyHarnessService_WorkflowGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LuckyHarnessServiceServer).WorkflowGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LuckyHarnessService_WorkflowGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LuckyHarnessServiceServer).WorkflowGet(ctx, req.(*WorkflowGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LuckyHarnessService_WorkflowList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LuckyHarnessServiceServer).WorkflowList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LuckyHarnessService_WorkflowList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LuckyHarnessServiceServer).WorkflowList(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LuckyHarnessService_WorkflowDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LuckyHarnessServiceServer).WorkflowDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LuckyHarnessService_WorkflowDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LuckyHarnessServiceServer).WorkflowDelete(ctx, req.(*WorkflowDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LuckyHarnessService_WorkflowStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LuckyHarnessServiceServer).WorkflowStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LuckyHarnessService_WorkflowStart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LuckyHarnessServiceServer).WorkflowStart(ctx, req.(*WorkflowStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LuckyHarnessService_WorkflowInstanceGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowInstanceGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LuckyHarnessServiceServer).WorkflowInstanceGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LuckyHarnessService_WorkflowInstanceGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LuckyHarnessServiceServer).WorkflowInstanceGet(ctx, req.(*WorkflowInstanceGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LuckyHarnessService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LuckyHarnessServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LuckyHarnessService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LuckyHarnessServiceServer).HealthCheck(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// LuckyHarnessService_ServiceDesc is the grpc.ServiceDesc for LuckyHarnessService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LuckyHarnessService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "luckyharness.LuckyHarnessService",
	HandlerType: (*LuckyHarnessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Chat",
			Handler:    _LuckyHarnessService_Chat_Handler,
		},
		{
			MethodName: "MemoryStore",
			Handler:    _LuckyHarnessService_MemoryStore_Handler,
		},
		{
			MethodName: "MemoryRecall",
			Handler:    _LuckyHarnessService_MemoryRecall_Handler,
		},
		{
			MethodName: "MemoryList",
			Handler:    _LuckyHarnessService_MemoryList_Handler,
		},
		{
			MethodName: "MemoryDelete",
			Handler:    _LuckyHarnessService_MemoryDelete_Handler,
		},
		{
			MethodName: "RAGIndex",
			Handler:    _LuckyHarnessService_RAGIndex_Handler,
		},
		{
			MethodName: "RAGSearch",
			Handler:    _LuckyHarnessService_RAGSearch_Handler,
		},
		{
			MethodName: "WorkflowCreate",
			Handler:    _LuckyHarnessService_WorkflowCreate_Handler,
		},
		{
			MethodName: "WorkflowGet",
			Handler:    _LuckyHarnessService_WorkflowGet_Handler,
		},
		{
			MethodName: "WorkflowList",
			Handler:    _LuckyHarnessService_WorkflowList_Handler,
		},
		{
			MethodName: "WorkflowDelete",
			Handler:    _LuckyHarnessService_WorkflowDelete_Handler,
		},
		{
			MethodName: "WorkflowStart",
			Handler:    _LuckyHarnessService_WorkflowStart_Handler,
		},
		{
			MethodName: "WorkflowInstanceGet",
			Handler:    _LuckyHarnessService_WorkflowInstanceGet_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _LuckyHarnessService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatStream",
			Handler:       _LuckyHarnessService_ChatStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "luckyharness.proto",
}
